security:
  oauth2:
    cliet:
      clientId: 249247462803777
        clientSecret: 564111662417b97bcb8bc2b62641b31a
          accessTokenUri: https://graph.facebook.com/oauth/access-token
            userAuthorizationUri: https://www.facebook.com/dialog/oauth
              tokenName: oauth-token
                authenticationScheme: query
                  clientAuthenticationScheme: form
              resource:
                userInfoUri: https://graph.facebook.com/me

